---
# roles/fm-monitor/tasks/silentjack.yml

- name: The pagkages.
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - silentjack
  tags:
    - silentjack

- name: Directory .local/bin.
  become: true
  ansible.builtin.file:
    path: "/home/{{ device_user }}/.local/bin"
    state: directory
    owner: "{{ device_user }}"
    group: "{{ device_user_group }}"
    mode: "0755"
  tags:
    - silentjack

- name: Silence response action script.
  become: true
  ansible.builtin.copy:
    src: silence-detected
    dest: /home/{{ device_user }}/.local/bin/silence-detected
    owner: "{{ device_user }}"
    group: "{{ device_user_group }}"
    mode: "0755"
  tags:
    - silentjack

- name: The silentjack service.
  remote_user: "{{ device_user }}"
  ansible.builtin.command:
    argv:
      - systemctl
      - --user
      - enable
      - silentjack.service
  changed_when: false
  tags:
    - silentjack
