---
# roles/fm-monitor/tasks/vu-meters.yml
#
# Unlike other aspects, this task sets up a user "autostart" file; it
# launchs when the user logs in.

- name: The pagkages.
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - meterbridge
  tags:
    - vu-meters

- name: Directory .local/bin.
  become: true
  ansible.builtin.file:
    path: "/home/{{ device_user }}/.local/bin"
    state: directory
    owner: "{{ device_user }}"
    group: "{{ device_user_group }}"
    mode: "0755"
  tags:
    - vu-meters

- name: Directory .config/autostart.
  become: true
  ansible.builtin.file:
    path: "/home/{{ device_user }}/.config/autostart"
    state: directory
    owner: "{{ device_user }}"
    group: "{{ device_user_group }}"
    mode: "0755"
  tags:
    - vu-meters

- name: VU meters launch script.
  become: true
  ansible.builtin.copy:
    src: vu-meters
    dest: /home/{{ device_user }}/.local/bin/vu-meters
    owner: "{{ device_user }}"
    group: "{{ device_user_group }}"
    mode: "0755"
  tags:
    - vu-meters

- name: VU meters autostart desktop file.
  become: true
  ansible.builtin.template:
    src: vu-meters.desktop.j2
    dest: "/home/{{ device_user }}/.config/autostart/vu-meters.desktop"
    owner: "{{ device_user }}"
    group: "{{ device_user_group }}"
    mode: "0644"
  tags:
    - vu-meters
